### PR TITLE
Add Configuration Saving/Loading

### PR DESCRIPTION
**Pull request by kraln**
Addresses #23.

LaiNES now can save and load configuration. At the moment, it's the size
of the window, and the key bindings.

Saving and loading is done to a file in the same folder as LaiNES.

This commit adds SimpleINI as a git submodule.

### CODE REVIEW

**Comment by AndreaOrru** [comment]
This looks really good, thanks.

Just one thing - usually Unix applications put their configurations in ~/.config, any reason not to?

**Comment by kraln** [comment]
No reason. http://unix.stackexchange.com/questions/68721/where-should-user-configuration-files-go seems to indicate creating a sub-folder in ~/.config (if ~/.config exists)

**Comment by kraln** [comment]
Updated, support *nix home directories and pulled the config stuff out of the GUI

**Comment by kraln** [comment]
My one concern is that this is very 'c' and not so much c++. I think that's okay for now but it will need to be refactored to a proper class and clean c++ when it grows larger

**Comment by kraln** [comment]
(rebased + squished)

**Comment by AndreaOrru** [comment]
Merged. Awesome!

**Pull request merged**
